export const conditions = [
  { name: 'blinded', id: 0 },
  { name: 'deafened', id: 1 },
  { name: 'frightened', id: 2 },
  { name: 'grappled', id: 3 },
  { name: 'incapacitated', id: 4 },
  { name: 'invisible', id: 5 },
  { name: 'paralised', id: 6 },
  { name: 'petrified', id: 7 },
  { name: 'poisoned', id: 8 },
  { name: 'prone', id: 9 },
  { name: 'restrained', id: 10 },
  { name: 'stunned', id: 11 },
  { name: 'unconscious', id: 12 },
  { name: 'exhausted', id: 14 },
];
